/**
 *  解释型模拟器
 *  整体架构  解释执行 + JIT 执行
 */

#include "Hiemu.h"

static void func_empty(state_t *state, insn_t *insn) {
    // do nothing  具体指令的工作
    printf("This instruction is not implemented\n");
}

typedef void (func_t) (state_t *, insn_t *);

static func_t *funcs[] = { /* 与指令数一致 */
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    func_empty,
    
};

void exec_block_interp(state_t *state) {
    static insn_t insn = {0};
    while(true) {
        u32 data = *(u32 *)TO_HOST(state->pc);
        insn_decode(&insn, data);

        funcs[insn.type](state, &insn);
        state->gp_regs[zero] = 0;

        if(insn.cont) break;

        state->pc += insn.rvc ? 2 : 4;
    }
}
